version: '3.1'
services:
  # Redis Backend
  redis:
    image: redis
    # uncomment to expose redis
    # ports:
    #   - 6379:6379
  # Exposed service
  captcha-micoservice:
    build: .
    ports:
      - 9090:9090
    environment:
      - REDIS_CONNECT_STRING=redis:6379
    links:
      - redis