version: '3.2'
services:
  # Redis Backend
  redis:
    image: redis
    ports:
      - 127.0.0.1:6379:6379
    restart: always
  # Exposed service
  captcha-micoservice:
    build: .
    ports:
      - 127.0.0.1:9090:9090
    environment:
      - REDIS_CONNECT_STRING=redis:6379
    links:
      - redis
    restart: always
